// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkbibprgxcmlgyspthha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYmlicHJneGNtbGd5c3B0aGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjM4NDIsImV4cCI6MjA4MzkzOTg0Mn0.hMXgFBwS3zMuleIEDvBIzTvcH_9plwckWu-uFcndEl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});